### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by Witti2** [heimseiten/contao-universal-toggler-bundle#2]
Hello, we always get an error in the console.

Contao 4.9.12

`Uncaught TypeError: e.querySelector(...) is null
    setActiveState https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:108
    setActiveState https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:102
    setInitialStatus https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:85
    activateClickToggler https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:12
    activateClickToggler https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:11
    start https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:5
    <anonymous> https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:1
`
`setActiveState https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:108
    forEach self-hosted:206
    setActiveState https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:102
    setInitialStatus https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:85
    activateClickToggler https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:12
    forEach self-hosted:206
    activateClickToggler https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:11
    start https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:5
    <anonym> https://www.digiphotopro.de/bundles/heimseitencontaouniversaltoggler/universal-toggler.js:1
`

**Comment by heimseiten** [comment]
Thanks. Should be solved with the new version 2.1.2

**Comment by Witti2** [comment]
Thanks, works perfect now

greetings
